name: Scheduled online check

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/scheduled.yml
  schedule:
    # Once every day at 1AM
    - cron: "0 1 * * *"

concurrency:
  group: scheduled
  cancel-in-progress: true

permissions:
  issues: write

jobs:
  create_matrix:
    if: startsWith( github.repository, 'Homebrew/' )
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
    outputs:
      json: ${{ steps.matrix.outputs.json }}
    env:
      TEST_COUNT: 50
      TAP: homebrew/core
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: true
          cask: false
          test-bot: false

      - name: Generate matrix
        id: matrix
        run: |
          formula="$(find "$(brew --repo "${TAP}")/Formula" -type f | shuf -n "${TEST_COUNT}" | xargs -I{} basename {} .rb)"
          # shellcheck disable=SC2086
          json="$(
            brew info --json=v2 $formula |
            jq --compact-output '[.formulae[] | select(.deprecated == false and .disabled == false) | .name]'
          )"
          echo "json=${json}" >> "$GITHUB_OUTPUT"

  audit_online:
    if: startsWith( github.repository, 'Homebrew/' )
    runs-on: ${{ matrix.os }}
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
    needs: create_matrix
    name: "Online check (${{ matrix.os }}): ${{ matrix.formula }}"
    env:
      HOMEBREW_GITHUB_API_TOKEN: "${{ github.token }}"
      GH_TOKEN: "${{ github.token }}"
      REPORTING_ISSUE: 139929
    strategy:
      fail-fast: false
      matrix:
        formula: ${{ fromJson(needs.create_matrix.outputs.json) }}
        os: [ubuntu-22.04]
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: true
          cask: false
          test-bot: false

      - name: Check formula source is not archived.
        id: archived
        if: matrix.os != 'macos-latest'
        run: brew audit --online --skip-style --only github_repository_archived,gitlab_repository_archived ${{ matrix.formula }}

      - name: Report online issues
        if: ${{ failure() && steps.archived.conclusion == 'failure' }}
        run: |
          gh issue comment "$REPORTING_ISSUE" \
                           --repo homebrew/homebrew-core \
                           --body "${{ matrix.formula }} should be archived. Check ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Check formula for unavailable homepage.
        id: homepage
        if: matrix.os != 'macos-latest'
        run: brew audit --online --skip-style --only homepage ${{ matrix.formula }}

      - name: Report homepage issues
        if: ${{ failure() && steps.homepage.conclusion == 'failure' }}
        run:  |
          gh issue comment "$REPORTING_ISSUE" \
                           --repo homebrew/homebrew-core \
                           --body "${{ matrix.formula }} has homepage issues. Check ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Check formula for missing sources.
        id: fetch
        if: matrix.os != 'macos-latest'
        run: brew fetch -s ${{ matrix.formula }}

      - name: Report fetch issues
        if: ${{ failure() && steps.fetch.conclusion == 'failure' }}
        run:  |
          gh issue comment "$REPORTING_ISSUE" \
                           --repo homebrew/homebrew-core \
                           --body "${{ matrix.formula }} source has problems. Check ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
